{"uuid":"b8af043d-d9ec-4163-8435-60711410accf","historyId":"7626a4cd9554efd38bab33b6b09f2dbf","fullName":"API.Test.LoginApiTest.Test_Invaid_Login_Api","labels":[{"name":"package","value":"API.Test.LoginApiTest"},{"name":"testClass","value":"API.Test.LoginApiTest"},{"name":"testMethod","value":"Test_Invaid_Login_Api"},{"name":"parentSuite","value":"Regression Suite"},{"name":"suite","value":"API Test"},{"name":"subSuite","value":"API.Test.LoginApiTest"},{"name":"host","value":"DESKTOP-QRLIM7I"},{"name":"thread","value":"11404@DESKTOP-QRLIM7I.TestNG-tests-2(28)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"Test_Invaid_Login_Api","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [404] but found [200]","trace":"java.lang.AssertionError: expected [404] but found [200]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1578)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:150)\r\n\tat org.testng.Assert.assertEquals(Assert.java:132)\r\n\tat org.testng.Assert.assertEquals(Assert.java:1419)\r\n\tat org.testng.Assert.assertEquals(Assert.java:1383)\r\n\tat org.testng.Assert.assertEquals(Assert.java:1429)\r\n\tat API.Test.LoginApiTest.Test_Invaid_Login_Api(LoginApiTest.java:45)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\r\n\tat org.testng.TestRunner.run(TestRunner.java:614)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)\r\n\tat org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)\r\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1570)\r\n"},"stage":"finished","description":"This test case verifies that a user cannot  login with invalid credentials.","steps":[],"attachments":[],"parameters":[{"name":"arg1","value":"123fd!456"},{"name":"arg0","value":"UUU@gmail.com"}],"start":1737482422033,"stop":1737482429736}